version: '3.8'

networks:
  streaming-net:
    driver: bridge

services:
  # --- Redpanda (Kafka Alternative) ---
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-0
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr=plaintext://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr=plaintext://redpanda-0:29092,external://localhost:9092
    ports:
      - "9092:9092"
    networks:
      - streaming-net

  # --- Redpanda Console (UI) ---
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      - KAFKA_BROKERS=redpanda-0:29092
    ports:
      - "8080:8080"
    networks:
      - streaming-net
    depends_on:
      - redpanda
    

  # --- Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - streaming-net
    depends_on:
      - redpanda
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin 
    volumes:
    - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus 
    ports:
      - "9090:9090"
    networks:
      - streaming-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - streaming-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - streaming-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - streaming-net

  python-producer:
    build: .
    container_name: python-producer
    depends_on:
      - redpanda
    networks:
      - streaming-net

volumes:
  prometheus_data:
  grafana_data: